package presentation;
import business.exceptions.PasswordIncorretaException;
import business.exceptions.UserIncorretoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import business.MediaCenter_Facade;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author via
 */
public class EditarPassword extends javax.swing.JFrame {

    /**
     * Creates new form EditarPassword
     */
     public EditarPassword(MediaCenter_Facade mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mail = new java.awt.TextField();
        ok = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 33, 67));
        jPanel1.setForeground(new java.awt.Color(36, 33, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 300));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email_.png"))); // NOI18N
        jLabel1.setText("Email");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 130, 180, 49);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password_antiga.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 220, 420, 43);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nova_password.png"))); // NOI18N
        jLabel3.setText("Nova Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 290, 380, 43);
        jPanel1.add(mail);
        mail.setBounds(470, 150, 170, 30);

        ok.setFont(new java.awt.Font("Yu Gothic Medium", 3, 16)); // NOI18N
        ok.setText("editar password");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(470, 360, 170, 35);
        jPanel1.add(password);
        password.setBounds(470, 230, 170, 26);
        jPanel1.add(password2);
        password2.setBounds(470, 300, 170, 26);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HOLE.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(540, 10, 60, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar password.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 10, 490, 70);

        jSeparator1.setBackground(new java.awt.Color(244, 255, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 80, 680, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atrás.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 370, 55, 55);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        
        
        checkPassword();        
    }//GEN-LAST:event_okActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        EditarConta atras = new EditarConta(mf);
        atras.setVisible(true);
        atras.pack();
        atras.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public void checkPassword(){ 
        
        
        
        //se o nome/passwords estiverem vazios
        if(mail.getText().equals("") || password.getPassword().equals("") || password2.getPassword().equals("") ){
        JOptionPane.showMessageDialog(rootPane,"Campos por preencher", "Erro",1); 
            
        }
        //se a password antiga for igual a nova
        else if (String.valueOf(password.getPassword()).equals(String.valueOf(password2.getPassword()))){
        JOptionPane.showMessageDialog(rootPane,"É a mesma password. Caso não queira mudar a password deixe o campo em branco", "Erro",1);  
           
        }
       /* else
             if(name2.getText().equals("") && String.valueOf(password2.getPassword()).equals("") && mail2.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane,"Para a edição ter sucesso é preciso EDITAR um campo existente (Nome,Mail ou Password)", "Erro",1); 
            
             }
        */ 
      
      
            
        
        
        
       else
           
            try{
       
       
       mf.confirmaLogin(mail.getText(), String.valueOf(password.getPassword()),"x");
       mf.editContaPassword(mail.getText(),String.valueOf(password2.getPassword()));
        JOptionPane.showMessageDialog (this,"Password editada :) ");
    }           
    catch (UserIncorretoException ex ) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog (this,"Email de utilizador incorreto");
              
        } catch (PasswordIncorretaException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog (this,"Password de utilizador incorreto");
        }
       
           
           
    }
    
  
    MediaCenter_Facade mf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField mail;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    // End of variables declaration//GEN-END:variables
}
