package presentation;
import business.exceptions.UserIncorretoException;
import javax.swing.JOptionPane;
import business.MediaCenter_Facade;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author via
 */
public class EditarEmail extends javax.swing.JFrame{


    /**
     * Creates new form EditarEmail
     */
    public EditarEmail(MediaCenter_Facade mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mail = new java.awt.TextField();
        mail2 = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 33, 67));
        jPanel1.setForeground(new java.awt.Color(36, 33, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 300));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email_.png"))); // NOI18N
        jLabel1.setText("Email");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 90, 170, 49);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo_email.png"))); // NOI18N
        jLabel2.setText("Novo Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 190, 280, 43);

        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 3, 16)); // NOI18N
        jButton1.setText("Editar!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 300, 100, 35);
        jPanel1.add(mail);
        mail.setBounds(310, 100, 190, 20);
        jPanel1.add(mail2);
        mail2.setBounds(310, 190, 190, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_mail.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 10, 363, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atrás.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 300, 55, 55);

        jSeparator1.setBackground(new java.awt.Color(244, 255, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 52, 520, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void checkEmail() { 
        
        //se o nome/password estiverem vazios
        if(mail.getText().equals("") || mail2.getText().equals("") ){
        JOptionPane.showMessageDialog(rootPane,"Campos por preencher", "Erro",1); 
            
        }
        /*se a password antiga for igual a nova
        else if (String.valueOf(password.getPassword()).equals(String.valueOf(password2.getPassword()))){
        JOptionPane.showMessageDialog(rootPane,"É a mesma password. Caso não queira mudar a password deixe o campo em branco", "Erro",1);  
            return false;
        }*/
       /* else
             if(name2.getText().equals("") && String.valueOf(password2.getPassword()).equals("") && mail2.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane,"Para a edição ter sucesso é preciso EDITAR um campo existente (Nome,Mail ou Password)", "Erro",1); 
            
             }
        */ 
        else 
       if (mail.getText().equals(mail2.getText())) { 
        JOptionPane.showMessageDialog(rootPane,"Os E-mails são idênticos", "Erro",1);  
       }
       
       else{
           try{
        mf.editContaEmail(mail.getText(),mail2.getText());
        //mf.editContaNome(email2,nome2);
        //edita a password da conta já com o novo mail editado
        //mf.editContaPassword(email2,pwd2);
        JOptionPane.showMessageDialog (this,"Todos os parâmetros da conta editados ");
    }           
    catch (UserIncorretoException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog (this,"Email de utilizador incorreto");
              
        }
       }
           
          
       
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        checkEmail();
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        EditarConta atras = new EditarConta(mf);
        atras.setVisible(true);
        atras.pack();
        atras.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

   
    MediaCenter_Facade mf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField mail;
    private java.awt.TextField mail2;
    // End of variables declaration//GEN-END:variables
}
