package presentation;
import business.exceptions.UserIncorretoException;
import javax.swing.JOptionPane;
import business.MediaCenter_Facade;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author via
 */
public class EditarNome extends javax.swing.JDialog {

    /**
     * Creates new form EditarNome
     */
     public EditarNome(MediaCenter_Facade mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mail = new java.awt.TextField();
        nome = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 33, 67));
        jPanel1.setForeground(new java.awt.Color(36, 33, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 300));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email_.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 90, 170, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo_nome.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 160, 260, 43);
        jPanel1.add(mail);
        mail.setBounds(330, 100, 210, 30);
        jPanel1.add(nome);
        nome.setBounds(330, 160, 210, 30);

        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 3, 16)); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 220, 210, 35);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar nome.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 0, 330, 50);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 0, 2);

        jSeparator2.setBackground(new java.awt.Color(244, 255, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 60, 590, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atrás.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 210, 55, 55);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        checkNome();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        EditarConta atras = new EditarConta(mf);
        atras.setVisible(true);
        atras.pack();
        atras.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void checkNome() { 
        
        //se o nome/password estiverem vazios
        if(mail.getText().equals("") || nome.getText().equals("") ){
        JOptionPane.showMessageDialog(rootPane,"Campos por preencher", "Erro",1); 
            
        }
        /*se a password antiga for igual a nova
        else if (String.valueOf(password.getPassword()).equals(String.valueOf(password2.getPassword()))){
        JOptionPane.showMessageDialog(rootPane,"É a mesma password. Caso não queira mudar a password deixe o campo em branco", "Erro",1);  
            return false;
        }*/
       /* else
             if(name2.getText().equals("") && String.valueOf(password2.getPassword()).equals("") && mail2.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane,"Para a edição ter sucesso é preciso EDITAR um campo existente (Nome,Mail ou Password)", "Erro",1); 
            
             }
        */ 
      
       else{
           try{
       
       mf.editContaNome(mail.getText(),nome.getText());
        //edita a password da conta já com o novo mail editado
        //mf.editContaPassword(email2,pwd2);
        JOptionPane.showMessageDialog (this,"Nome editado :) ");
    }           
    catch (UserIncorretoException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog (this,"Email de utilizador incorreto");
              
        }
       }
           
          
       
    }
   
    MediaCenter_Facade mf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.TextField mail;
    private java.awt.TextField nome;
    // End of variables declaration//GEN-END:variables
}
