package presentation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import business.exceptions.PasswordIncorretaException;
import business.exceptions.UserIncorretoException;
import javax.swing.JOptionPane;
import business.MediaCenter_Facade; 

/**
 *
 * @author via
 */
public class MainPage extends javax.swing.JDialog {
    
   
    /**
     * Creates new form MainPage
     */
    public MainPage(MediaCenter_Facade mf) {
        this.mf = mf;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        try {
            email =(java.awt.TextField)java.beans.Beans.instantiate(getClass().getClassLoader(), "presentation.MainPage_textField1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        password = new javax.swing.JPasswordField();
        roles = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 38, 67));
        jPanel1.setForeground(new java.awt.Color(36, 33, 67));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(39, 38, 67));
        jPanel3.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone password.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 0, 50, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(410, 420, 60, 40);

        jPanel2.setBackground(new java.awt.Color(39, 38, 67));
        jPanel2.setForeground(new java.awt.Color(39, 38, 67));
        jPanel2.setMaximumSize(new java.awt.Dimension(25, 25));
        jPanel2.setMinimumSize(new java.awt.Dimension(25, 25));
        jPanel2.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-astronaut-48.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 20, 50, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(410, 220, 70, 80);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 370, 270, 45);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 690, 100, 90);

        login.setBackground(new java.awt.Color(36, 33, 67));
        login.setFont(new java.awt.Font("Yu Gothic Medium", 3, 16)); // NOI18N
        login.setForeground(new java.awt.Color(36, 33, 67));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(240, 640, 110, 35);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 200, 160, 45);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(170, 260, 240, 30);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(170, 430, 240, 26);

        roles.setFont(new java.awt.Font("Sitka Subheading", 2, 16)); // NOI18N
        roles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[escolha o seu estatututo]", "Admin", "Utilizador", "Convidado" }));
        roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolesActionPerformed(evt);
            }
        });
        jPanel1.add(roles);
        roles.setBounds(180, 570, 230, 27);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mediacenter.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 10, 570, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 90, 210, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/role.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 520, 230, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trademark.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(310, 750, 289, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rank.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 560, 51, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
                                                   
                                                   
        String mail = email.getText();
        String pw = String.valueOf(password.getPassword());
        String rolezin = roles.getSelectedItem().toString();
       
        if(rolezin.equals("Convidado")){
            this.mf.setGuest();
            Playlists pl = new Playlists(this.mf);      
            pl.setVisible(true);
            pl.pack();
            pl.setLocationRelativeTo(null);
            this.dispose();
        }
        else if(mail.equals("") || pw.equals("") || rolezin.equals("[escolha o seu estatututo]")){
            JOptionPane.showMessageDialog(rootPane,"Campos por preencher", "Erro",1);
        }
        else{
            try {
                rolezin = roles.getSelectedItem().toString();
                String tipo = "U";
                if(rolezin.equals("Admin")){
                    tipo = "A";
                }
                mf.login(mail,pw,tipo);
                JOptionPane.showMessageDialog (this,"Login efetuado com sucesso");
                if(rolezin.equals("Utilizador")){
                    AfterLogin after = new AfterLogin(this.mf);      
                    after.setVisible(true);
                    after.pack();
                    after.setLocationRelativeTo(null);
                    this.dispose();
                }
                else if(rolezin.equals("Admin")){
                    music_vid admin = new music_vid(this.mf);      
                    admin.setVisible(true);
                    admin.pack();
                    admin.setLocationRelativeTo(null);
                    this.dispose();
                }
            }
            catch (UserIncorretoException | PasswordIncorretaException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog (this,"Password ou nome de utilizador incorreto");   
            }     
        }
    }//GEN-LAST:event_loginActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
       
    }//GEN-LAST:event_emailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesActionPerformed
        email.setEditable(false);
        password.setEditable(false);
    }//GEN-LAST:event_rolesActionPerformed
    
  
    /**
     * @param args the command line arguments
     */
   

    MediaCenter_Facade mf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> roles;
    // End of variables declaration//GEN-END:variables
}
