/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.MediaCenter_Facade;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author joaonunoabreu
 */
public class MenuPlaylist extends javax.swing.JDialog {

    /**
     * Creates new form MenuPlaylist
     */
    public MenuPlaylist(MediaCenter_Facade mf) {
        this.mf = mf;
        initComponents();
        TableColumnModel tcm = tabela.getColumnModel();
        tcm.removeColumn(tcm.getColumn(4));
        tcm.removeColumn(tcm.getColumn(4));
        cb.addItemListener(new ItemChangeListener());
        addPlist();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        Carregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Play = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 33, 67));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/introduzir genero.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 110, 380, 37);

        cb.setBackground(new java.awt.Color(36, 33, 67));
        cb.setForeground(new java.awt.Color(255, 255, 255));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        jPanel1.add(cb);
        cb.setBounds(650, 300, 130, 26);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(550, 200, 272, 24);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(550, 130, 272, 24);

        Carregar.setFont(new java.awt.Font("Yu Gothic Medium", 3, 16)); // NOI18N
        Carregar.setForeground(new java.awt.Color(36, 33, 67));
        Carregar.setText("Carregar");
        Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarActionPerformed(evt);
            }
        });
        jPanel1.add(Carregar);
        Carregar.setBounds(740, 370, 150, 36);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "autor", "nome", "género", "tempo", "id", "path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 270, 610, 300);

        lb.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb);
        lb.setBounds(730, 300, 260, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/criar.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(850, 110, 65, 70);

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play (1).png"))); // NOI18N
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });
        jPanel1.add(Play);
        Play.setBounds(860, 190, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Playlist.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 10, 240, 50);

        jLabel9.setBackground(new java.awt.Color(0, 51, 102));
        jLabel9.setDisplayedMnemonic('l');
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portal.png"))); // NOI18N
        jLabel9.setToolTipText("logout ");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(920, 10, 50, 52);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_nome_playlist.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 190, 510, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atrás.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 55, 55);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 80, 990, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int selectedRow = tabela.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

    }//GEN-LAST:event_tabelaMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    private void CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        String[] parts2 = lb.getText().split(" ");
        List<String> med = mf.idPlaylistToMedias(Integer.parseInt(parts2[1]));
        Object rowData[] = new Object[6];
        
        for(int i = 0;i < med.size(); i++){
            String[] parts = med.get(i).split("\n");
            rowData[0] = parts[2];
            rowData[1] = parts[1];
            rowData[2] = parts[4];
            rowData[3] = parts[3];
            rowData[4] = parts[0];
            rowData[5] = parts[5];
            model.addRow(rowData);
        }
    }//GEN-LAST:event_CarregarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        TableColumnModel tcm = tabela.getColumnModel();
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        List<String> med = mf.musicaG(jTextField1.getText());
        Object rowData[] = new Object[6];
        
        int id = mf.addPlaylist(jTextField2.getText());
        
        for(int i = 0;i < med.size(); i++){
            String[] parts = med.get(i).split("\n");
            rowData[0] = parts[2];
            rowData[1] = parts[1];
            rowData[2] = parts[4];
            rowData[3] = parts[3];
            rowData[4] = parts[0];
            rowData[5] = parts[5];
            model.addRow(rowData);
            mf.addBigGeral_has_Playlist(Integer.parseInt(parts[0]),id);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        String path = (String) model.getValueAt(tabela.convertRowIndexToModel(tabela.getSelectedRow()),5);
        try {
            Runtime.getRuntime().exec("open -a /Applications/VLC.app " + path);

        } catch (IOException ex) {
            Logger.getLogger(Playlists.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PlayMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:

        int resposta =JOptionPane.showConfirmDialog(this,"Farto de estar por cá?","Finalizar sessão?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if(resposta == JOptionPane.YES_OPTION){
            mf.logout();
            MainPage main =new MainPage(mf);
            main.setVisible(true);
            main.pack();
            main.setLocationRelativeTo(null);

            this.dispose();}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        AfterLogin atras = new AfterLogin(mf);
        atras.setVisible(true);
        atras.pack();
        atras.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    class ItemChangeListener implements ItemListener{
    @Override
    public void itemStateChanged(ItemEvent event) {
       if (event.getStateChange() == ItemEvent.SELECTED) {
            String x = String.valueOf(cb.getSelectedItem());
            lb.setText(x);
        }
    }       
    }
    
    private void addPlist(){
        List<String> med = mf.pList();
        for(int i = 0;i < med.size(); i++){
            cb.addItem(med.get(i));
        }
    }

    MediaCenter_Facade mf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carregar;
    private javax.swing.JLabel Play;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb;
    public static javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
